import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,FileText,Table2,FolderOpen,BookOpen,Settings,Plus,Search,LogOut,Printer,Download,Trash2,Save,ChevronRight,RefreshCw,Menu,X,ClipboardList,BadgeCheck,IndianRupee,Upload,FolderPlus,ArrowLeft,ExternalLink} from 'lucide-react';
import './styles.css';

const api=async(path,opts={})=>{const r=await fetch('/api'+path,{credentials:'include',...opts});let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d.error||'Request failed');return d};
const post=(p,b)=>api(p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
const put=(p,b)=>api(p,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
const money=n=>`₹ ${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const inrWords=n=>{const x=Math.round(Number(n||0)); if(!x)return'Zero Only'; const ones=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen']; const tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety']; const two=v=>v<20?ones[v]:tens[Math.floor(v/10)]+(v%10?' '+ones[v%10]:''); let s=''; if(x>=10000000){s+=two(Math.floor(x/10000000))+' Crore ';x%=10000000} if(x>=100000){s+=two(Math.floor(x/100000))+' Lakh ';x%=100000} if(x>=1000){s+=two(Math.floor(x/1000))+' Thousand ';x%=1000} if(x>=100){s+=ones[Math.floor(x/100)]+' Hundred ';x%=100} if(x) s+=(s?'and ':'')+two(x)+' '; return s.trim()+' Only'};

const defaultCla=['The work is required for reliable operation and preventive maintenance of the equipment.','The proposed quantity is based on past consumption/experience and the expected requirement during the financial year.','The rates are based on the applicable division cost data / approved rate reference and remain editable for verification.','The work/material is technically suitable for the identified equipment and service conditions.'];
const defaultScope=[
 {title:'Cleaning and replacement of MOT Duplex filters & Jack oil filters',steps:['Transport the required material and T&P from central/section stores to the work spot.','Charging the standby MOT filter through equalizing valve.','Changing over of the oil flow to standby filter.','Draining of oil in the filter.','Removal of the filter cover and filter element.','Cleaning of filter inside area.','Fixing the spare filter element in the filter.','Replacement of gaskets, if any gaskets are damaged.','Fixing the filter cover.','Oil filling and venting in the cleaned filter.','Cleaning of the removed filter element for future utilization.','Necessary safety precautions should be taken by the contractor.']},
 {title:'Cleaning and replacement of MOT Bucket filter',steps:['Transport required material and T&P from stores to work spot.','Dismantling of top cover of filter.','Removing bucket filter from MOT.','Erection of spare filter in the MOT.','Fixing the top cover of the MOT bucket filter.','Cleaning of the removed filter.','Necessary safety precautions should be taken by the contractor.']},
 {title:'Cleaning and replacement of Vacuum pump filters',steps:['Transport the required material and T&P from stores to work spot.','Charging the standby vacuum pump filter through equalizing valve.','Changing over the oil flow to standby filter.','Draining of oil in the filter.','Removal of the filter cover and filter element.','Cleaning of filter inside area.','Fixing the spare filter element in the filter.','Replacement of gaskets, if any gaskets are damaged.','Fixing the filter cover.','Oil filling and venting in the cleaned filter.','Cleaning of the removed filter element for future utilization.','Necessary safety precautions should be taken by the contractor.']},
 {title:'Cleaning and replacement of seal oil pump filters',steps:['Transport the required material and T&P from stores to work spot.','Charging the standby seal oil pump filter through equalizing valve.','Changing over the oil flow to standby filter.','Draining of oil in the filter.','Removal of the filter cover and filter element.','Cleaning of filter inside area.','Fixing the spare filter element in the filter.','Replacement of gaskets, if any gaskets are damaged.','Fixing the filter cover.','Oil filling and venting in the cleaned filter.','Cleaning of the removed filter element for future utilization.','Necessary safety precautions should be taken by the contractor.']},
 {title:'Cleaning of HPSU strainers (TG, LPBP, HPBP)',steps:['Transport the required material and T&P from central/section stores to the work spot.','Charging the standby filter through equalizing valve.','Changing over of the oil flow to standby filter.','Draining of oil in the filter.','Removal of the filter cover and filter element.','Cleaning of filter inside area.','Fixing the spare filter element in the filter.','Replacement of gaskets, if any gaskets are damaged.','Fixing the filter cover.','Oil filling and venting in the cleaned filter.','Cleaning of the removed filter element for future utilization.','Necessary safety precautions should be taken by the contractor.']},
 {title:'Cleaning of Primary water system strainers',steps:['Transport the required material and T&P from central/section stores to the work spot.','Charging the standby filter through equalizing valve.','Changing over of the oil flow to standby filter.','Draining of oil in the filter.','Removal of the filter cover and filter element.','Cleaning of filter inside area.','Fixing the spare filter element in the filter.','Replacement of gaskets, if any gaskets are damaged.','Fixing the filter cover.','Oil filling and venting in the cleaned filter.','Cleaning of the removed filter element for future utilization.','Necessary safety precautions should be taken by the contractor.']},
 {title:'Gland leaks arresting and minor repairs of water, steam, air line valves',steps:['Transport the required material and T&P from central/section stores to the work spot.','Isolating the valves to stop flow of fluid.','Arrangement of scaffolding.','Replacement of gland/rope rings with new one.','Tightening / replacement of flange gaskets.','Replacement/tightening of bonnet gasket.','Restoration of the isolated valves.','Necessary safety precautions should be taken by the contractor.']},
 {title:'Oil, water and air leaks arresting',steps:['Transport the required material and T&P from central/section stores to the work spot.','Isolating the valves to stop flow of fluid.','Arrangement of scaffolding.','Cleaning of the pipes/valves area.','Clamping/welding of the leakage area.','Restoration of the isolated valves.','Necessary safety precautions should be taken by the contractor.']},
 {title:'Minor welding works',steps:['Transport the required material and T&P from central/section stores to the work spot.','Isolating the valves to stop flow of fluid.','Arrangement of scaffolding.','Cleaning of the pipes/valves area.','Edge preparation of the pipe/plate.','Welding of the pipe/plate/joint.','Restoration of the isolated valves.','Necessary safety precautions should be taken by the contractor.']}
];

function App(){
 const [user,setUser]=useState(null); const [page,setPage]=useState('dashboard'); const [side,setSide]=useState(true); const [selected,setSelected]=useState(null); const [toast,setToast]=useState('');
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2500)};
 useEffect(()=>{api('/auth/me').then(x=>setUser(x.user)).catch(()=>{})},[]);
 if(!user)return <Auth onLogin={setUser}/>;
 return <div className="app-shell"><aside className={'sidebar '+(!side?'closed':'')}><div className="brand"><div className="brand-mark">DE</div><div><b>Division Estimate</b><span>Suite</span></div></div><nav>{[['dashboard','Dashboard',LayoutDashboard],['estimates','Estimates',FileText],['new','Create Estimate',Plus],['rates','Rates & Data',IndianRupee],['docs','Documents',ClipboardList],['files','File Explorer',FolderOpen],['guide','How to Create',BookOpen]].map(([k,l,I])=><button className={page===k?'active':''} onClick={()=>{setPage(k);setSelected(null)}} key={k}><I size={18}/><span>{l}</span></button>)}</nav><div className="side-bottom"><div className="user-card"><div className="avatar">{(user.name||'U').slice(0,1).toUpperCase()}</div><div><b>{user.name}</b><small>{user.role}</small></div></div><button onClick={async()=>{await api('/auth/logout',{method:'POST'});location.reload()}}><LogOut size={17}/> Sign out</button></div></aside>
 <main className="main"><header><button className="icon-btn" onClick={()=>setSide(v=>!v)}>{side?<X size={18}/>:<Menu size={18}/>}</button><div className="crumb">TM & CAM / Stage-V <ChevronRight size={14}/> {page==='dashboard'?'Overview':page[0].toUpperCase()+page.slice(1)}</div><div className="header-actions"><span className="pill">FY 2026-27</span><Settings size={18}/></div></header><div className="content">
 {page==='dashboard'&&<Dashboard onOpen={(p,id)=>{setPage(p);setSelected(id)}}/>}
 {page==='estimates'&&<Estimates onOpen={(id)=>{setSelected(id);setPage('new')}} onNew={()=>{setSelected(null);setPage('new')}}/>}
 {page==='new'&&<EstimateEditor id={selected} onSaved={id=>{setSelected(id);notify('Estimate saved');}} notify={notify}/>} 
 {page==='rates'&&<Rates notify={notify}/>} 
 {page==='docs'&&<Documents selected={selected} onSelect={setSelected} />}
 {page==='files'&&<FilesPage notify={notify}/>} 
 {page==='guide'&&<Guide/>}
 </div>{toast&&<div className="toast">{toast}</div>}</main></div>
}

function Auth({onLogin}){const [mode,setMode]=useState('login');const [form,setForm]=useState({name:'',email:'admin@example.com',password:'Admin@123',division:'TM & CAM / Stage-V'});const [err,setErr]=useState('');const submit=async e=>{e.preventDefault();setErr('');try{const r=await post(mode==='login'?'/auth/login':'/auth/register',form);onLogin(r.user)}catch(x){setErr(x.message)}};return <div className="auth-wrap"><div className="auth-card"><div className="auth-logo">DE</div><h1>Division Estimate Suite</h1><p>Estimates, indents and supporting documents in one controlled workspace.</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{mode==='register'&&<input placeholder="Division / office" value={form.division} onChange={e=>setForm({...form,division:e.target.value})}/>} {err&&<div className="error">{err}</div>}<button className="primary wide">{mode==='login'?'Sign in':'Create account'}</button></form><button className="link-btn" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Register':'Already registered? Sign in'}</button><small className="demo-hint">Demo: admin@example.com / Admin@123</small></div></div>}

function Dashboard({onOpen}){const [s,setS]=useState(null);const [recent,setRecent]=useState([]);useEffect(()=>{Promise.all([api('/stats'),api('/estimates')]).then(([a,b])=>{setS(a);setRecent(b.slice(0,5))})},[]);return <><div className="page-head"><div><div className="eyebrow">CONTROL CENTRE</div><h1>Division documentation workspace</h1><p>Build a single estimate and keep all linked documents synchronized.</p></div><button className="primary" onClick={()=>onOpen('new',null)}><Plus size={17}/> New estimate</button></div><div className="cards">{[['Estimates',s?.estimates||0,'All saved estimates'],['Drafts',s?.drafts||0,'Needs completion'],['Rate items',s?.rates||0,'Active catalogue'],['Files',s?.files||0,'Reference library']].map(([a,b,c])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><div className="grid-2"><section className="panel"><div className="panel-head"><h3>Recent estimates</h3><button className="ghost" onClick={()=>onOpen('estimates')}>View all</button></div>{recent.length?recent.map(e=><div className="list-row" key={e._id} onClick={()=>onOpen('new',e._id)}><div className="list-icon"><FileText size={18}/></div><div className="grow"><b>{e.workTitle||'Untitled estimate'}</b><span>{e.prNo||'No PR'} · {e.financialYear||'2026-27'}</span></div><span className={'status '+e.status.toLowerCase()}>{e.status}</span><span>{money(e.calc?.total)}</span></div>):<div className="empty">No estimates yet. Start from the sample rate catalogue.</div>}</section><section className="panel quick"><div className="panel-head"><h3>Quick actions</h3></div>{[['Create from text','Paste a work requirement and build a draft.','new'],['Manage rates','Edit 2026-27 rates and references.','rates'],['File explorer','Upload sanctioned files, PDFs and references.','files'],['Workflow guide','See the recommended indent sequence.','guide']].map(([a,b,p])=><button key={p} onClick={()=>onOpen(p)} className="quick-row"><div><b>{a}</b><span>{b}</span></div><ChevronRight size={17}/></button>)}</section></div></>}

function Estimates({onOpen,onNew}){const [data,setData]=useState([]);const [q,setQ]=useState('');useEffect(()=>{api('/estimates').then(setData)},[]);const rows=useMemo(()=>data.filter(e=>JSON.stringify(e).toLowerCase().includes(q.toLowerCase())),[data,q]);return <><div className="page-head"><div><div className="eyebrow">ESTIMATE REGISTER</div><h1>Estimates</h1><p>One source of truth for quantities, rates, CLA and document output.</p></div><button className="primary" onClick={onNew}><Plus size={17}/> Create estimate</button></div><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search title, PR, unit or cost centre" value={q} onChange={e=>setQ(e.target.value)}/></div><button className="ghost"><RefreshCw size={16}/> Refresh</button></div><section className="panel table-panel"><table><thead><tr><th>Work / estimate</th><th>PR / Indent</th><th>FY</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(e=><tr key={e._id}><td><b>{e.workTitle||'Untitled'}</b><span>{e.station||'Station not set'} · {e.unit||'Unit not set'}</span></td><td>{e.prNo||'—'}<span>{e.indentNo||'—'}</span></td><td>{e.financialYear||'2026-27'}</td><td>{money(e.calc?.total)}</td><td><span className={'status '+e.status.toLowerCase()}>{e.status}</span></td><td><button className="icon-btn" onClick={()=>onOpen(e._id)}><ExternalLink size={16}/></button></td></tr>)}{!rows.length&&<tr><td colSpan="6"><div className="empty">No matching estimates.</div></td></tr>}</tbody></table></section></>}

function EstimateEditor({id,onSaved,notify}){const [rates,setRates]=useState([]);const blank={projectNo:'',workTitle:'',division:'TM & CAM / Stage-V',station:'Dr.NTTPS, Ibrahimpatnam',stage:'Stage-V',unit:'Unit-8',financialYear:'2026-27',prNo:'',indentNo:'',letterNo:'',date:new Date().toISOString().slice(0,10),costCentre:'',manufacturer:'',scope:'',cla:[...defaultCla],notes:'',rows:[],charges:{supervision:10,esi:3.25,epf:13,gst:18},status:'Draft'};const [e,setE]=useState(blank);const [tab,setTab]=useState('details');const [brief,setBrief]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{api('/rates').then(setRates); if(id)api('/estimates/'+id).then(x=>setE({...x,charges:{supervision:10,esi:3.25,epf:13,gst:18,...(x.charges||{})}}))},[id]);
 const calc=useMemo(()=>{const base=e.rows.reduce((s,r)=>s+Number(r.qty||0)*Number(r.rate||0),0);const sv=base*Number(e.charges.supervision||0)/100, esi=base*Number(e.charges.esi||0)/100, epf=base*Number(e.charges.epf||0)/100;const taxable=base+sv+esi+epf;const gst=taxable*Number(e.charges.gst||0)/100;return {base,supervision:sv,esi,epf,gst,total:taxable+gst}},[e]);
 const autoCreate=()=>{const t=brief.toLowerCase();const keys=[['mot duplex',['mot duplex','jack oil','duplex filter']],['bucket',['bucket filter','mot bucket']],['vacuum',['vacuum pump']],['seal oil',['seal oil']],['hpsu',['hpsu','lpbp','hpbp']],['primary water',['primary water']],['gland',['gland','steam air line valve','gland leak']],['leaks',['oil water air leak','leaks arresting']],['welding',['welding','weld']]];let picks=[];for(const [k,terms] of keys){if(terms.some(v=>t.includes(v))){const r=rates.find(x=>x.description.toLowerCase().includes(k));if(r)picks.push(r)}}if(!picks.length)picks=rates.filter(r=>t.includes('filter')?r.description.toLowerCase().includes('filter'):r.category==='Labour').slice(0,3);const rows=(picks.length?picks:rates.slice(0,3)).map((r,i)=>({sl:i+1,code:r.code,description:r.description,qty:1,unit:r.unit,rate:r.rate,source:r.reference}));const scopeParts=picks.map(r=>{const found=defaultScope.find(s=>r.description.toLowerCase().startsWith(s.title.toLowerCase().slice(0,18)))||defaultScope.find(s=>r.description.toLowerCase().includes(s.title.toLowerCase().split(' ')[0]));return found?found.title+'\n'+found.steps.map((x,j)=>String.fromCharCode(97+j)+') '+x).join('\n'):r.description}).join('\n\n');setE(x=>({...x,workTitle:brief.replace(/^create( an)? estimate (for)?/i,'').trim()||x.workTitle,scope:scopeParts||brief,rows}));setTab('rows');notify?.('Draft created from your brief');};
 const save=async()=>{setBusy(true);try{const saved=id?await put('/estimates/'+id,e):await post('/estimates',e);onSaved(saved._id);setE(saved);notify?.('Saved');}catch(x){alert(x.message)}finally{setBusy(false)}};
 const update=(k,v)=>setE(x=>({...x,[k]:v})); const addRow=r=>setE(x=>({...x,rows:[...x.rows,{sl:x.rows.length+1,code:r?.code||'',description:r?.description||'',qty:1,unit:r?.unit||'Each',rate:r?.rate||0,source:r?.reference||''}]}));
 return <div><div className="page-head"><div><div className="eyebrow">{id?'EDIT ESTIMATE':'NEW ESTIMATE'}</div><h1>{e.workTitle||'Create an estimate'}</h1><p>Edit every field; linked document templates use the same record automatically.</p></div><div className="head-btns"><button className="ghost" onClick={()=>window.print()}><Printer size={16}/> Print current view</button><button className="primary" onClick={save} disabled={busy}><Save size={16}/> {busy?'Saving…':'Save estimate'}</button></div></div>
 <div className="workbench"><section className="panel editor"><div className="tabs">{[['details','1. Job'],['rows','2. Estimate table'],['cla','3. CLA & scope'],['documents','4. Documents']].map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</div>
 {tab==='details'&&<><div className="callout"><b>Quick create</b><span>Describe the requirement in plain text. The system will match the rate catalogue and create editable rows.</span><div className="quick-create"><input value={brief} onChange={x=>setBrief(x.target.value)} placeholder="e.g. Create estimate for MOT duplex filter cleaning for Unit-8, FY 2026-27"/><button className="primary" onClick={autoCreate}>Build draft</button></div></div><FieldGrid data={e} onChange={update}/></>}
 {tab==='rows'&&<><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Find a catalogue item" onKeyDown={ev=>{if(ev.key==='Enter'){const r=rates.find(r=>r.description.toLowerCase().includes(ev.target.value.toLowerCase())||r.code.toLowerCase().includes(ev.target.value.toLowerCase()));if(r)addRow(r)}}}/></div><button className="ghost" onClick={()=>addRow()}><Plus size={16}/> Blank row</button></div><table className="edit-table"><thead><tr><th>Sl.</th><th>Description</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Amount</th><th></th></tr></thead><tbody>{e.rows.map((r,i)=><tr key={i}><td>{i+1}</td><td><textarea value={r.description} onChange={ev=>{const rows=[...e.rows];rows[i].description=ev.target.value;setE({...e,rows})}}/><small>{r.code||'No material/activity code'} · {r.source||'Manual'}</small></td><td><input type="number" value={r.qty} onChange={ev=>{const rows=[...e.rows];rows[i].qty=ev.target.value;setE({...e,rows})}}/></td><td><input value={r.unit||''} onChange={ev=>{const rows=[...e.rows];rows[i].unit=ev.target.value;setE({...e,rows})}}/></td><td><input type="number" value={r.rate} onChange={ev=>{const rows=[...e.rows];rows[i].rate=ev.target.value;setE({...e,rows})}}/></td><td>{money(Number(r.qty||0)*Number(r.rate||0))}</td><td><button className="icon-btn danger" onClick={()=>setE({...e,rows:e.rows.filter((_,j)=>j!==i)})}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!e.rows.length&&<div className="empty">No rows yet. Use quick create or add a blank row.</div>}<div className="calc-box"><div><span>Base labour/material</span><b>{money(calc.base)}</b></div><label>Supervision % <input type="number" value={e.charges.supervision} onChange={ev=>update('charges',{...e.charges,supervision:ev.target.value})}/></label><label>ESI % <input type="number" value={e.charges.esi} onChange={ev=>update('charges',{...e.charges,esi:ev.target.value})}/></label><label>EPF % <input type="number" value={e.charges.epf} onChange={ev=>update('charges',{...e.charges,epf:ev.target.value})}/></label><label>GST % <input type="number" value={e.charges.gst} onChange={ev=>update('charges',{...e.charges,gst:ev.target.value})}/></label><div className="total"><span>Estimated amount</span><strong>{money(calc.total)}</strong></div><div className="muted">{inrWords(calc.total)}</div></div></>}
 {tab==='cla'&&<><div className="section-title"><h3>CLA points</h3><p>These points are stored once and reused in the covering letter, estimate report, scope and other generated documents.</p></div>{e.cla.map((c,i)=><div className="cla-row" key={i}><span>{i+1}</span><textarea value={c} onChange={ev=>{const a=[...e.cla];a[i]=ev.target.value;update('cla',a)}}/><button className="icon-btn danger" onClick={()=>update('cla',e.cla.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div>)}<button className="ghost" onClick={()=>update('cla',[...e.cla,'New CLA point'])}><Plus size={16}/> Add CLA point</button><div className="section-title scope-head"><h3>Scope of work</h3><p>Use the seeded 2026-27 scope as a starting point. You can edit or delete any step.</p></div><textarea className="scope-editor" value={e.scope} onChange={ev=>update('scope',ev.target.value)} placeholder="Describe scope / operational requirement..."/></>}
 {tab==='documents'&&<DocumentCards e={e} calc={calc}/>}</section><aside className="side-summary"><div className="sticky-card"><h3>Estimate summary</h3><div className="summary-line"><span>Rows</span><b>{e.rows.length}</b></div><div className="summary-line"><span>Base</span><b>{money(calc.base)}</b></div><div className="summary-line"><span>GST</span><b>{money(calc.gst)}</b></div><div className="summary-total"><span>Total</span><strong>{money(calc.total)}</strong></div><p>{inrWords(calc.total)}</p><button className="primary wide" onClick={save}><Save size={16}/> Save & sync</button><div className="sync-note"><BadgeCheck size={16}/> CLA, quantity, rates and amount are linked across generated documents.</div></div></aside></div></div>
}

function FieldGrid({data,onChange}){const f=[['workTitle','Work / estimate title'],['station','Station / location'],['division','Division'],['stage','Stage'],['unit','Unit'],['financialYear','Financial year'],['prNo','PR No.'],['indentNo','Indent No.'],['letterNo','Letter No.'],['date','Document date'],['costCentre','Cost centre'],['manufacturer','OEM / manufacturer']];return <div className="field-grid">{f.map(([k,l])=><label key={k}>{l}<input value={data[k]||''} onChange={e=>onChange(k,e.target.value)}/></label>)}<label className="span-2">Manufacturer / technical description notes<textarea value={data.notes||''} onChange={e=>onChange('notes',e.target.value)}/></label></div>}

function DocumentCards({e,calc}){const items=[['covering','Covering letter','Official-style covering letter with live amount and CLA.'],['report','Report to accompany the estimate','Justification, need, resource statement and cost centre.'],['detailed','Detailed estimate','Editable source rows rendered as print-ready A4.'],['indent','Indent','Indented procurement request with supporting details.'],['oes','OES / proprietary form','OEM/OES/single-source certificate layout.'],['screening','Screening committee','Committee recommendation with members/signature lines.'],['scope','Scope of work','Nine work packages based on the supplied scope.']];return <div className="doc-grid">{items.map(([t,n,d])=><div className="doc-card" key={t}><div><FileText size={19}/><h3>{n}</h3><p>{d}</p></div><button className="primary" onClick={()=>printDoc(t,e,calc)}><Printer size={15}/> Print</button></div>)}</div>}

function printDoc(type,e,calc){const esc=x=>String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');let title='',body='';const head=`<div class="letterhead"><h1>ANDHRA PRADESH POWER GENERATION CORPORATION LIMITED</h1><div>${esc(e.division||'TM & CAM / Stage-V')} · ${esc(e.station||'Dr.NTTPS, Ibrahimpatnam')}</div></div>`;const meta=`<div class="doc-meta"><span><b>Work:</b> ${esc(e.workTitle)}</span><span><b>FY:</b> ${esc(e.financialYear)}</span><span><b>PR No.:</b> ${esc(e.prNo||'—')}</span><span><b>Indent No.:</b> ${esc(e.indentNo||'—')}</span></div>`;
 if(type==='covering'){title='COVERING LETTER';body=`${head}<div class="fromto"><div>From<br/><b>The Executive Engineer</b><br/>TM & CAM Division, ${esc(e.stage||'Stage-V')}<br/>${esc(e.station)}</div><div>To<br/><b>The Superintending Engineer</b><br/>${esc(e.stage||'Stage-V')}, O&M<br/>${esc(e.station)}</div></div><p><b>Sub:</b> ${esc(e.workTitle)} – Reg.</p>${meta}<p>The estimate for an amount of <b>${money(calc.total)}</b> (<b>${inrWords(calc.total)}</b>) is submitted for the above work during ${esc(e.financialYear)}.</p><p>As per the requirement stated and the supporting technical details, the work is proposed to ensure reliable operation, preventive maintenance and readiness of the identified equipment.</p><h4>Enclosures</h4><ol><li>Report to accompany the estimate</li><li>Detailed estimate</li><li>Scope of work</li><li>Other supporting forms, wherever applicable</li></ol><p class="signature">Yours faithfully,<br/><br/><b>Executive Engineer</b><br/>TM & CAM Division, ${esc(e.stage||'Stage-V')}</p>`}
 if(type==='report'){title='REPORT TO ACCOMPANY THE ESTIMATE';body=`${head}<div class="amount">Estimated amount: <b>${money(calc.total)}</b></div>${meta}<p>The estimate envisages charges for <b>${esc(e.workTitle)}</b> for the year ${esc(e.financialYear)} in ${esc(e.division)}.</p><p>The proposal is required to attend repairs, periodic and preventive maintenance and associated works for smooth and reliable operation of the unit.</p><h3>Justification / need</h3><ul>${e.cla.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><p><b>Resource statement:</b> Work shall be carried out with the required technical/operational staff, tools & plant and safety precautions as applicable to the work.</p><p><b>Cost centre:</b> ${esc(e.costCentre||'To be entered')}</p><p class="signature"><b>Executive Engineer</b><br/>TM & CAM Division, ${esc(e.stage||'Stage-V')}</p>`}
 if(type==='detailed'){title='DETAILED ESTIMATE';body=`${head}<h2>DETAILED ESTIMATE</h2><p><b>Name of the work:</b> ${esc(e.workTitle)}</p><table><thead><tr><th>Sl.No</th><th>Description</th><th>Qty</th><th>Rate (Rs.)</th><th>Total (Rs.)</th></tr></thead><tbody>${e.rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.description)}<br/><small>${esc(r.code||'')}</small></td><td>${esc(r.qty)}</td><td>${Number(r.rate||0).toLocaleString('en-IN',{minimumFractionDigits:2})}</td><td>${money(Number(r.qty||0)*Number(r.rate||0)).replace('₹ ','')}</td></tr>`).join('')}</tbody><tfoot><tr><td colspan="4"><b>Base</b></td><td>${money(calc.base).replace('₹ ','')}</td></tr><tr><td colspan="4">Supervision</td><td>${money(calc.supervision).replace('₹ ','')}</td></tr><tr><td colspan="4">ESI</td><td>${money(calc.esi).replace('₹ ','')}</td></tr><tr><td colspan="4">EPF</td><td>${money(calc.epf).replace('₹ ','')}</td></tr><tr><td colspan="4">GST</td><td>${money(calc.gst).replace('₹ ','')}</td></tr><tr><td colspan="4"><b>Total estimated amount</b></td><td><b>${money(calc.total).replace('₹ ','')}</b></td></tr></tfoot></table><p><b>Amount in words:</b> ${inrWords(calc.total)}</p><h3>CLA / points</h3><ol>${e.cla.map(c=>`<li>${esc(c)}</li>`).join('')}</ol><p class="signature"><b>Executive Engineer</b></p>`}
 if(type==='indent'){title='INDENT';body=`${head}<h2>INDENT FOR PROCUREMENT / WORK</h2>${meta}<p><b>Requirement:</b> ${esc(e.workTitle)}</p><p><b>Estimated value:</b> ${money(calc.total)}</p><table><thead><tr><th>Sl.No</th><th>Material / Service description</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${e.rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.description)}</td><td>${esc(r.qty)}</td><td>${esc(r.unit)}</td><td>${money(r.rate)}</td><td>${money(Number(r.qty||0)*Number(r.rate||0))}</td></tr>`).join('')}</tbody></table><h3>Why this indent?</h3><ul>${e.cla.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><p><b>Estimated amount in words:</b> ${inrWords(calc.total)}</p><p class="signature"><b>Indenting Officer / Executive Engineer</b></p>`}
 if(type==='oes'){title='PROPRIETARY ARTICLE / OEM / OES / STANDARDIZATION / SINGLE SOURCE PROCUREMENT CERTIFICATE';body=`${head}<h2>${title}</h2><table class="form"><tr><th>1. Manufacturer / Supplier Name and Address</th><td>${esc(e.manufacturer||'Enter OEM / supplier details')}</td></tr><tr><th>2. Description of articles</th><td>${e.rows.map((r,i)=>`${i+1}. ${esc(r.description)} · Material/Code: ${esc(r.code||'—')}`).join('<br>')}</td></tr><tr><th>3. Indigenous or imported</th><td>Indigenous / Imported: as applicable</td></tr><tr><th>4. Indian agent, if any</th><td>As applicable</td></tr><tr><th>5. Quantity requisitioned</th><td>As per PR / indent: ${esc(e.prNo||'—')}</td></tr><tr><th>6. Estimated value</th><td>${money(calc.total)}</td></tr><tr><th>7. Department Sl.No. and date</th><td>${esc(e.letterNo||'—')} · ${esc(e.date||'')}</td></tr></table><p>To the best of our knowledge, the item(s) covered in the above requisition are proprietary/OEM articles or otherwise require procurement on the stated basis as technically applicable.</p><p class="signature">Signature<br/><br/>Name & Designation</p>`}
 if(type==='screening'){title='INDENT SCREENING COMMITTEE';body=`${head}<h2>${title}</h2><p><b>Sub:</b> Indent for ${esc(e.workTitle)} – Reg.</p><p><b>Ref:</b> PR No. ${esc(e.prNo||'—')} · Date: ${esc(e.date||'')}</p><p>An indent cited above is received for procurement/work with an estimated value of <b>${money(calc.total)}</b>. The committee, on verification of the indent and examination of the requirement, recommends processing the same for placing the purchase order / work order as per applicable procedure.</p><table><thead><tr><th>Sl.No</th><th>Designation of the Committee member</th><th>Signature</th></tr></thead><tbody><tr><td>1</td><td>SE / Stage-V / Dr. NTTPS</td><td></td></tr><tr><td>2</td><td>SE / A&M / Dr. NTTPS</td><td></td></tr><tr><td>3</td><td>GM (Finance) / Dr. NTTPS</td><td></td></tr></tbody></table>`}
 if(type==='scope'){title='SCOPE OF WORK';const scopeHtml=e.scope&&e.scope.trim()?e.scope.split(/\n\s*\n/).map((part,i)=>`<section><h3>${i+1}. Work package</h3><p>${esc(part).replace(/\n/g,'<br>')}</p></section>`).join(''):defaultScope.map((s,i)=>`<section><h3>${i+1}. ${esc(s.title)}</h3><ol type="a">${s.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>`).join('');body=`${head}<h2>${title}</h2><p><b>Name of the work:</b> ${esc(e.workTitle)}</p><p><b>Note:</b> The contractor must provide sufficient staff, tools & plant and observe all required safety precautions. The detailed scope below is editable and intended as a working baseline.</p>${scopeHtml}<h3>Project-specific CLA</h3><ul>${e.cla.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`}
 const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><title>${title}</title><style>@page{size:A4;margin:18mm 17mm}body{font-family:"Times New Roman",serif;font-size:12pt;line-height:1.35;color:#111}.letterhead{text-align:center;border-bottom:1px solid #111;padding-bottom:8px;margin-bottom:18px}.letterhead h1{font-size:15pt;margin:0 0 5px}.fromto{display:grid;grid-template-columns:1fr 1fr;gap:30px}.doc-meta{display:grid;grid-template-columns:1fr 1fr;border:1px solid #222;padding:8px;gap:4px;margin:12px 0}h2,h3{text-align:center;text-transform:uppercase}p{margin:12px 0}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{border:1px solid #222;padding:6px;vertical-align:top}th{font-weight:bold}.form th{text-align:left;width:34%}.amount{text-align:right;font-size:14pt}.signature{text-align:right;margin-top:40px}.scope{page-break-before:auto}li{margin:4px 0}.quick{background:#f6f6f6}.muted{color:#555}@media print{.signature{break-inside:avoid}}</style></head><body>${body}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}

function Rates({notify}){const [r,setR]=useState([]);const [q,setQ]=useState('');const [editing,setEditing]=useState(null);useEffect(()=>{api('/rates').then(setR)},[]);const add=async()=>{const n=await post('/rates',{code:'NEW',description:'New rate item',unit:'Each',category:'Labour',rate:0,year:'2026-27',reference:'Division approved rate reference'});setR([...r,n]);setEditing(n)};const save=async()=>{const x=await put('/rates/'+editing._id,editing);setR(r.map(z=>z._id===x._id?x:z));setEditing(null);notify('Rate updated')};return <><div className="page-head"><div><div className="eyebrow">RATE CATALOGUE</div><h1>Rates & data</h1><p>Seeded from the supplied 2026-27 reference screenshots. Verify against the latest approved division source before issue.</p></div><button className="primary" onClick={add}><Plus size={16}/> Add rate</button></div><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search code or description" value={q} onChange={e=>setQ(e.target.value)}/></div></div><section className="panel table-panel"><table><thead><tr><th>Code</th><th>Description</th><th>Category</th><th>Year</th><th>Rate</th><th>Reference</th><th></th></tr></thead><tbody>{r.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())).map(x=>editing?._id===x._id?<tr key={x._id}><td><input value={editing.code} onChange={e=>setEditing({...editing,code:e.target.value})}/></td><td><input value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></td><td><input value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/></td><td><input value={editing.year} onChange={e=>setEditing({...editing,year:e.target.value})}/></td><td><input type="number" value={editing.rate} onChange={e=>setEditing({...editing,rate:e.target.value})}/></td><td><input value={editing.reference||''} onChange={e=>setEditing({...editing,reference:e.target.value})}/></td><td><button className="primary" onClick={save}>Save</button></td></tr>:<tr key={x._id}><td><b>{x.code}</b></td><td>{x.description}<span>{x.unit}</span></td><td>{x.category}</td><td>{x.year}</td><td>{money(x.rate)}</td><td>{x.reference}</td><td><button className="ghost" onClick={()=>setEditing(x)}>Edit</button></td></tr>)}</tbody></table></section></>}

function Documents({selected,onSelect}){const [ests,setEsts]=useState([]);useEffect(()=>{api('/estimates').then(setEsts)},[]);return <><div className="page-head"><div><div className="eyebrow">DOCUMENT CENTRE</div><h1>Document bundles</h1><p>Choose an estimate and generate any linked document without re-keying values.</p></div></div><div className="doc-select"><select value={selected||''} onChange={e=>onSelect(e.target.value)}><option value="">Select estimate…</option>{ests.map(e=><option key={e._id} value={e._id}>{e.workTitle||'Untitled'} · {e.prNo||'No PR'}</option>)}</select></div>{selected?<SelectedDocs id={selected}/>:<div className="empty panel">Select an estimate to open its document set.</div>}</>}
function SelectedDocs({id}){const [x,setX]=useState(null);useEffect(()=>{api('/estimates/'+id).then(setX)},[id]);if(!x)return <div className="panel empty">Loading…</div>;return <section className="panel"><div className="panel-head"><div><h3>{x.workTitle}</h3><span>{money(x.calc?.total)} · {x.financialYear}</span></div><button className="primary" onClick={()=>['covering','report','detailed','indent','oes','screening','scope'].forEach((t,i)=>setTimeout(()=>printDoc(t,x,x.calc),i*350))}><Printer size={16}/> Print bundle</button></div><DocumentCards e={x} calc={x.calc}/></section>}

function FilesPage({notify}){const [folders,setFolders]=useState([]);const [files,setFiles]=useState([]);const [folder,setFolder]=useState(null);const [newFolder,setNewFolder]=useState('');const load=()=>Promise.all([api('/folders'),api('/files'+(folder?`?folderId=${folder}`:'?root=true'))]).then(([a,b])=>{setFolders(a);setFiles(b)});useEffect(load,[folder]);const up=async ev=>{const fd=new FormData();fd.append('file',ev.target.files[0]);if(folder)fd.append('folderId',folder);await fetch('/api/files/upload',{method:'POST',body:fd,credentials:'include'});load();notify('File uploaded')};return <><div className="page-head"><div><div className="eyebrow">REFERENCE LIBRARY</div><h1>File Explorer</h1><p>Store PDFs, rate sheets, sanctioned files and other references in MongoDB GridFS.</p></div><label className="primary upload-btn"><Upload size={16}/> Upload<input type="file" hidden onChange={up}/></label></div><div className="explorer"><div className="panel folder-pane"><div className="panel-head"><h3>Folders</h3><button className="icon-btn" onClick={async()=>{if(!newFolder)return;await post('/folders',{name:newFolder,parentId:folder});setNewFolder('');load()}}><FolderPlus size={17}/></button></div><div className="folder-create"><input placeholder="New folder" value={newFolder} onChange={e=>setNewFolder(e.target.value)}/></div><button className={'folder-row '+(!folder?'active':'')} onClick={()=>setFolder(null)}><FolderOpen size={16}/> Root</button>{folders.filter(f=>String(f.parentId||'')===String(folder||'')).map(f=><button key={f._id} className={'folder-row '+(folder===f._id?'active':'')} onClick={()=>setFolder(f._id)}><FolderOpen size={16}/> {f.name}</button>)}</div><div className="panel file-pane"><div className="panel-head"><div><h3>{folder?folders.find(f=>f._id===folder)?.name||'Folder':'Root'}</h3><span>{files.length} files</span></div></div><div className="file-grid">{files.map(f=><div className="file-card" key={f._id}><div className="file-icon"><FileText size={22}/></div><b title={f.name}>{f.name}</b><span>{Math.round(f.size/1024)} KB</span><div><a href={'/api/files/'+f._id+'/download'} target="_blank"><Download size={15}/></a></div></div>)}{!files.length&&<div className="empty">No files here. Upload PDF/Excel/Word references.</div>}</div></div></div></>}

function Guide(){return <><div className="page-head"><div><div className="eyebrow">WORKFLOW GUIDE</div><h1>How to create an indent</h1><p>A practical sequence for building the file set from one controlled estimate.</p></div></div><div className="guide-grid">{[['01','Create job master','Enter station, stage, unit, financial year, PR/indent references, cost centre and work title.'],['02','Pick the rate basis','Use the catalogue, verify the approved 2026-27 source and edit quantity/rate where justified.'],['03','Write the scope','Use the seeded scope packages or replace them with the exact technical scope for the job.'],['04','Set CLA points','Keep the reasons, technical conditions and resource statements in one place so they sync everywhere.'],['05','Review calculations','Check base, supervision, ESI, EPF, GST and the final amount in words.'],['06','Generate bundle','Print covering letter, report, detailed estimate, indent, OES/proprietary form and screening committee report.'],['07','Attach references','Store PR, QC approval, signed analysis sheet, vendor/OEM PDFs and other evidence in File Explorer.'],['08','Screen & issue','Use the screening committee sheet, capture signatures outside the system and issue the final approved document set.']].map(([n,h,b])=><section className="guide-card" key={n}><div className="number">{n}</div><h3>{h}</h3><p>{b}</p></section>)}</div><section className="panel"><div className="panel-head"><h3>Sample 2026-27 rates loaded</h3></div><div className="rate-strip"><span>₹2,893 MOT Duplex</span><span>₹7,957 MOT Bucket</span><span>₹1,086 Vacuum pump</span><span>₹1,807 Seal oil</span><span>₹2,893 HPSU</span><span>₹2,989 Primary water</span><span>₹2,305 Gland leaks</span><span>₹1,807 Oil/water/air leaks</span><span>₹1,309 Welding</span></div><p className="muted">These are seeded from the supplied screenshots as editable starting values, not a substitute for the currently sanctioned cost-data source.</p></section></>}

createRoot(document.getElementById('root')).render(<App/>);
